### ISSUE TITLE
Linking problems - Cross-compiler v1.0.24 - cross\lib\arm-linux\ is missing the "symlinked files" [fix inside]

### ISSUE THREAD

**Issue by BlumiMilch** [newpascal/newpascal#2]
Cross-compiling to ARM stopped working for me after switching from v1.0.22 to v1.0.24 because the linker couldn't find libusb-1.0 anymore.

The problem seems to be that the folder "cross\lib\arm-linux\" inside "CrossLinuxARM.rar" (release v1.0.24) is missing the symbolic links that usually populate Unix "lib"-folders. Under windows these symlinks can be emulated by using a plain copy of the file and it has been done this way in v1.0.22

A working solution for me was to copy the contents of the old v1.0.22 "CrossLinuxARM.rar:cross\lib\arm-linux*" folder to "C:\NewPascal\cross\lib\arm-linux\". After replacing the files from v1.0.24 everything worked as usual.

**Comment by LongDirtyAnimAlf** [comment]
Thanks for your report !
Indeed I changed the libraries between these versions to limit the size of the download.
It would help if you gave me somewhat more details.
E.g. did you only mis libusb.so (a direct copy of libusb.so.1 could solve) ?
Or were there more problems ?

**Comment by BlumiMilch** [comment]
I write down the steps involved in more detail, maybe it's useful for you and others later on.

One of the files in my project (a console application, no GUI) contains the following lines:

```
unit libusb;
interface
{$LINKLIB libusb-1.0}
...more code....
```

Compiling the project gave just a few lines including the following error:
**sstgw.lpr(790,1) Error: Error while linking**

Removing the tick at "Filter hints without Source Position" (right-click on Lazarus "Messages" window) allowed me to see where the linking failed:
**Debug: C:\NewPascal\cross\bin\arm-linux\arm-linux-gnueabihf-ld.exe: cannot find -lusb-1.0**

But "**C:\NewPascal\cross\lib\arm-linux\libusb-1.0.so.0**" existed, so I enabled verbose linker output with
Project ->  Project Options -> Compilation and Linking:
Enabled "**Pass options to linker...**" option and wrote "**--verbose**" (without the double-quotes) into the input box under the option.

Compiled again and "Messages" had a lot more output, this line was important:
**Debug: attempt to open C:\NewPascal\cross\lib\arm-linux\/libusb-1.0.so failed**

So the linker looked for the file "**libusb-1.0.so**". I copied "**libusb-1.0.so.0**" to "**libusb-1.0.so**" and recompiled...

...now even more libs were missing:
**Debug: C:\NewPascal\cross\bin\arm-linux\arm-linux-gnueabihf-ld.exe: warning: libpthread.so.0, needed by C:\NewPascal\cross\lib\arm-linux\/libusb-1.0.so, not found (try using -rpath or -rpath-link)**
...
**Debug: C:\NewPascal\cross\bin\arm-linux\arm-linux-gnueabihf-ld.exe: warning: libdl.so.2, needed by C:\NewPascal\cross\lib\arm-linux\/libudev.so.1, not found (try using -rpath or -rpath-link)**

and a whole lot of other errors (see attached file), so I decided to make it short and just copied the whole bunch from the old v1.0.22 lib into the new lib folder. (In fact I just renamed the new folder and made a NTFS-junction to the old folder)

[Compiler+Linker Messages.txt](https://github.com/newpascal/newpascal/files/522937/Compiler.Linker.Messages.txt)

**Comment by LongDirtyAnimAlf** [comment]
Many thanks. Very helpfull.
I will prepare a new release with correct libs.
ps: the new release will have a nice new feature: management operators for records !

**Comment by LongDirtyAnimAlf** [comment]
New releease. Reports welcome !

https://github.com/newpascal/newpascal/releases/tag/np_sc-v1.0.31
